spring:
  autoconfigure:

  jpa:
    hibernate:
      # ddl-auto: create-drop # 禁用此功能，交由 Flyway 管理
      ddl-auto: none
    show-sql: true

  # Flyway 配置
  flyway:
    enabled: true
    baseline-on-migrate: true # 如果数据库中已存在表，则将它们标记为基线

  # 数据源配置 (请替换为您的本地 MySQL 信息)
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Wyk060514.
    
    # HikariCP 连接池配置
    hikari:
      # 连接池大小配置
      maximum-pool-size: 10        # 最大连接数（开发环境适中）
      minimum-idle: 3              # 最小空闲连接数
      
      # 超时配置
      connection-timeout: 30000    # 获取连接超时时间（30秒）
      idle-timeout: 600000         # 空闲连接超时时间（10分钟）
      max-lifetime: 1800000        # 连接最大生命周期（30分钟）
      
      # 连接验证
      connection-test-query: SELECT 1
      validation-timeout: 5000     # 验证超时时间（5秒）
      
      # 连接池名称和监控
      pool-name: "DemoHikariPool"
      register-mbeans: true        # 启用JMX监控
      leak-detection-threshold: 60000  # 连接泄漏检测（1分钟）

  h2:
    console:
      enabled: true
